// app/layout.js or app/RootLayout.js
import { Inter } from 'next/font/google';
import '../globals.css'; // Import global styles
import Navbar from './Navbar';
import Footer from './Footer';

// Load the Inter font from Google Fonts
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect to Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        
        {/* Link to external fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Annapurna+SIL:wght@400;700&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Martel+Sans:wght@200;300;400;600;700;800;900&family=Martel:wght@200;300;400;600;700;800;900&family=Yatra+One&display=swap"
          rel="stylesheet"
        />
      </head>
      
      <body className={inter.className}>
        <Navbar /> {/* Global Navbar */}
        <main  className='pt-8'>{children}</main> {/* Main content area */}
        {/* <Footer />  */}
      </body>
    </html>
  );
}
