import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/component/Footer";
import Navbar from "./Navbar";

// Load the Inter font from Google Fonts
const inter = Inter({ subsets: ["latin"] });

// Metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect to Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        
        {/* Link to external fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Annapurna+SIL:wght@400;700&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Martel+Sans:wght@200;300;400;600;700;800;900&family=Martel:wght@200;300;400;600;700;800;900&family=Yatra+One&display=swap"
          rel="stylesheet"
        />
        
        {/* Link to manifest file */}
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
      </head>
      
      <body className={inter.className}>
        <Navbar /> {/* Navbar component */}
        <main>{children}</main> {/* The main content of the page */}
        
      </body>
    </html>
  );
}
