// app/layout.js or app/RootLayout.js
import { Inter } from 'next/font/google';
import '../globals.css'; // Import global styles
import Navbar from './Navbar';
import Footer from './Footer';

// Load the Inter font from Google Fonts
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar /> {/* Global Navbar */}
        <main>{children}</main> {/* Main content area */}
        <Footer /> {/* Global Footer */}
      </body>
    </html>
  );
}
